In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [4]:
df_customer=pd.read_csv('data/customers.csv')
df_loan=pd.read_csv('data/loans.csv')
df_bureau=pd.read_csv('data/bureau_data.csv')

In [6]:
print(df_bureau.shape)
print(df_customer.shape)
print(df_loan.shape)

(50000, 8)
(50000, 12)
(50000, 15)

In [7]:
df_loan.head(5)

  loan_id cust_id loan_purpose  ... disbursal_date  installment_start_dt  default
0  L00001  C00001         Auto  ...     2019-07-24            2019-08-10    False
1  L00002  C00002         Home  ...     2019-07-24            2019-08-15    False
2  L00003  C00003     Personal  ...     2019-07-24            2019-08-21    False
3  L00004  C00004     Personal  ...     2019-07-24            2019-08-09    False
4  L00005  C00005         Auto  ...     2019-07-24            2019-08-02    False

[5 rows x 15 columns]

In [8]:
df_customer.head(5)

  cust_id  age gender  ...       city        state  zipcode
0  C00001   44      M  ...      Delhi        Delhi   110001
1  C00002   38      M  ...    Chennai   Tamil Nadu   600001
2  C00003   46      F  ...    Kolkata  West Bengal   700001
3  C00004   55      F  ...  Bangalore    Karnataka   560001
4  C00005   37      M  ...       Pune  Maharashtra   411001

[5 rows x 12 columns]

In [9]:
df_bureau.head(5)

  cust_id  number_of_open_accounts  ...  enquiry_count  credit_utilization_ratio
0  C00001                        1  ...              3                         7
1  C00002                        3  ...              5                         4
2  C00003                        2  ...              6                        58
3  C00004                        3  ...              5                        26
4  C00005                        4  ...              5                        10

[5 rows x 8 columns]

# Megring dataset using primary key

In [11]:
df = pd.merge(df_bureau, df_customer, on='cust_id')#at once we can only merge 1 dataset
df = pd.merge(df, df_loan, on='cust_id')

df.head(3)

  cust_id  number_of_open_accounts  ...  installment_start_dt  default
0  C00001                        1  ...            2019-08-10    False
1  C00002                        3  ...            2019-08-15    False
2  C00003                        2  ...            2019-08-21    False

[3 rows x 33 columns]

In [12]:
df.shape

(50000, 33)

In [15]:
df.dtypes

cust_id                         object
number_of_open_accounts          int64
number_of_closed_accounts        int64
total_loan_months                int64
delinquent_months                int64
total_dpd                        int64
enquiry_count                    int64
credit_utilization_ratio         int64
age                              int64
gender                          object
marital_status                  object
employment_status               object
income                           int64
number_of_dependants             int64
residence_type                  object
years_at_current_address         int64
city                            object
state                           object
zipcode                          int64
loan_id                         object
loan_purpose                    object
loan_type                       object
sanction_amount                  int64
loan_amount                      int64
processing_fee                 float64
gst                              int64
net_disbursement                 int64
loan_tenure_months               int64
principal_outstanding            int64
bank_balance_at_application      int64
disbursal_date                  object
installment_start_dt            object
default                           bool
dtype: object

In [ ]:
df['default']=df['default'].astype(int)
df['default'].value_counts()# from this we can see class imbalance

default
0    45703
1     4297
Name: count, dtype: int64

In [17]:
df.describe()

       number_of_open_accounts  ...  bank_balance_at_application
count             50000.000000  ...                 5.000000e+04
mean                  2.500140  ...                 9.891264e+05
std                   1.118725  ...                 1.046072e+06
min                   1.000000  ...                 0.000000e+00
25%                   1.000000  ...                 2.870075e+05
50%                   3.000000  ...                 6.685250e+05
75%                   4.000000  ...                 1.238667e+06
max                   4.000000  ...                 7.846643e+06

[8 rows x 20 columns]

# Splitting data to avoid data leakage

In [19]:
x=df.drop('default',axis=1)
y=df.default

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=42)

In [20]:
df_train=pd.concat([x_train,y_train],axis=1)
df_test=pd.concat([x_test,y_test],axis=1)

df_train.shape,df_test.shape

((37500, 33), (12500, 33))